# Generated by Django 3.1.3 on 2020-12-03 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favourite',
            field=models.CharField(default='Add one fav book...', max_length=25),
        ),
    ]
