# Generated by Django 3.1.3 on 2020-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='username',
            field=models.CharField(default='Nimesh', max_length=30),
        ),
    ]
