# Generated by Django 3.1.3 on 2020-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201205_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='username',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
