# Generated by Django 3.1.3 on 2020-12-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201205_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='username',
        ),
    ]
