# Generated by Django 3.1.3 on 2020-12-05 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0012_auto_20201205_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
        migrations.AddField(
            model_name='poll',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
