# Generated by Django 3.1.3 on 2020-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20201205_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
        migrations.AddField(
            model_name='poll',
            name='username',
            field=models.CharField(default='Add your name...', max_length=30),
        ),
    ]
