# Generated by Django 3.1.3 on 2020-12-05 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20201205_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='username',
        ),
    ]
