# Generated by Django 3.1.3 on 2020-12-05 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_poll_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='username',
        ),
    ]
