# Generated by Django 3.1.3 on 2020-12-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_poll_category_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll_trigger',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
